# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will ru
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the jo
    steps:
      - run: |
          echo "github.repository=${{github.repository}}"
          echo "github.repository_ownere=${{github.repository_owner}}"
          echo "github.event.repository.name=${{github.event.repository.name}}"
          echo "github.sha=${{github.sha}}"
          echo "github.event.pull_request.head.sha=${{github.event.pull_request.head.sha}}"
          /usr/bin/git log -1 --format='%H'
